--------------------------------------------------------
-- Archivo creado  - domingo-junio-28-2020   
--------------------------------------------------------
DROP SEQUENCE "TODO"."CLIENTE_SEQ";
DROP TABLE "TODO"."ASESORIA" cascade constraints;
DROP TABLE "TODO"."CLIENTE" cascade constraints;
DROP TABLE "TODO"."MCLIENTE" cascade constraints;
DROP TABLE "TODO"."MEJORA" cascade constraints;
DROP TABLE "TODO"."MPROFESIONAL" cascade constraints;
DROP TABLE "TODO"."PERSONA" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TODO"."CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ASESORIA
--------------------------------------------------------

  CREATE TABLE "TODO"."ASESORIA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(20 BYTE), 
	"TASESORIA" VARCHAR2(200 BYTE), 
	"AESPECIAL" VARCHAR2(20 BYTE), 
	"ADETALLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "TODO"."CLIENTE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"FECHA" VARCHAR2(20 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"ACCIDENTE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MCLIENTE
--------------------------------------------------------

  CREATE TABLE "TODO"."MCLIENTE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEJORA
--------------------------------------------------------

  CREATE TABLE "TODO"."MEJORA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(400 BYTE), 
	"TASESORIA" VARCHAR2(200 BYTE), 
	"FECHA" VARCHAR2(20 BYTE), 
	"CAPACITACION" VARCHAR2(20 BYTE), 
	"DETALLEC" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MPROFESIONAL
--------------------------------------------------------

  CREATE TABLE "TODO"."MPROFESIONAL" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"RUT" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ACTIVIDAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "TODO"."PERSONA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"FECHA" VARCHAR2(20 BYTE), 
	"IDENTIFICADOR" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TODO.ASESORIA
SET DEFINE OFF;
Insert into TODO.ASESORIA (ID,NOMBRE,FECHA,TASESORIA,AESPECIAL,ADETALLE) values ('1','andres','APRESTO','12-20-2020','SI','sss');
Insert into TODO.ASESORIA (ID,NOMBRE,FECHA,TASESORIA,AESPECIAL,ADETALLE) values ('3','chupalin chamarro','2020-06-09','COACHING PSICOLOGICO','SI','cagao del mate');
REM INSERTING into TODO.CLIENTE
SET DEFINE OFF;
Insert into TODO.CLIENTE (ID,NOMBRE,FECHA,RUT,ACCIDENTE) values ('1','andres uribe negroni','2020-06-20','12524793-8','ATROPELLO');
Insert into TODO.CLIENTE (ID,NOMBRE,FECHA,RUT,ACCIDENTE) values ('2','pedrito','2020-06-10','12524793-8','INTOXICACION');
REM INSERTING into TODO.MCLIENTE
SET DEFINE OFF;
Insert into TODO.MCLIENTE (ID,NOMBRE,RUT,TELEFONO,EMAIL) values ('1','sodimac','12524793-8','784572222','pedrote@sodimac.cl');
REM INSERTING into TODO.MEJORA
SET DEFINE OFF;
Insert into TODO.MEJORA (ID,NOMBRE,TASESORIA,FECHA,CAPACITACION,DETALLEC) values ('1','andres uribe','MANTENCION','2020-06-10','no','capacitar uso de maquinaria');
Insert into TODO.MEJORA (ID,NOMBRE,TASESORIA,FECHA,CAPACITACION,DETALLEC) values ('3','Isaias','APRESTO','2020-05-27','si','quiere capacitacion en diseño de volantines');
REM INSERTING into TODO.MPROFESIONAL
SET DEFINE OFF;
Insert into TODO.MPROFESIONAL (ID,NOMBRE,RUT,TELEFONO,EMAIL,ACTIVIDAD) values ('1','JUAN soto','12524793-8','790944301','hhhhh@hahaha.cl','vago');
REM INSERTING into TODO.PERSONA
SET DEFINE OFF;
Insert into TODO.PERSONA (ID,NOMBRE,FECHA,IDENTIFICADOR,DESCRIPCION) values ('2','juan','20-12-205',null,null);
Insert into TODO.PERSONA (ID,NOMBRE,FECHA,IDENTIFICADOR,DESCRIPCION) values ('240181835','simona','20-12-2015','24018183-5','rrr');
--------------------------------------------------------
--  DDL for Index ASESORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."ASESORIA_PK" ON "TODO"."ASESORIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MCLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."MCLIENTE_PK" ON "TODO"."MCLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MPROFESIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."MPROFESIONAL_PK" ON "TODO"."MPROFESIONAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."PERSONA_PK" ON "TODO"."PERSONA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASESORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."ASESORIAS_PK" ON "TODO"."MEJORA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TODO"."CLIENTE_PK" ON "TODO"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TODO"."CLIENTE_TRG" 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TODO"."CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "TODO"."PERSONA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TODO"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "TODO"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MCLIENTE
--------------------------------------------------------

  ALTER TABLE "TODO"."MCLIENTE" ADD CONSTRAINT "MCLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO"."MCLIENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MPROFESIONAL
--------------------------------------------------------

  ALTER TABLE "TODO"."MPROFESIONAL" ADD CONSTRAINT "MPROFESIONAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO"."MPROFESIONAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEJORA
--------------------------------------------------------

  ALTER TABLE "TODO"."MEJORA" ADD CONSTRAINT "ASESORIAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO"."MEJORA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASESORIA
--------------------------------------------------------

  ALTER TABLE "TODO"."ASESORIA" ADD CONSTRAINT "ASESORIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO"."ASESORIA" MODIFY ("ID" NOT NULL ENABLE);
